### ISSUE TITLE
Add missing berries

### ISSUE THREAD

**Issue by Kyo91** [jake-white/VGC-2016-Damage-Calculator#10]
I noticed today that Figy berry, and I suspect other "heal 50%, confuse based on nature" berries are currently missing. With Figy berry on Gluttony Muk seeing use at the International challenge this weekend, it looks like these berries might be competitively viable this year and would be nice to be able to calc with them.

**Comment by ghost** [comment]
I'm working on this, but it's a little complicated. See the previous post for details.
