### ISSUE TITLE
Why hexadecimal values for calculation?

### ISSUE THREAD

**Issue by lynellf** [jake-white/VGC-2016-Damage-Calculator#102]
Just out of curiosity.

![image](https://user-images.githubusercontent.com/29016813/72232411-a64a5300-3586-11ea-9c5f-288dcef4d97d.png)

**Comment by jake-white** [comment]
Not my code, originated from https://github.com/smogon/damage-calc. Likely to avoid rounding errors but I won't claim to be certain.
