### ISSUE TITLE
Fishious Rend v Heliolisk

### ISSUE THREAD

**Issue by schmoounit** [jake-white/VGC-2016-Damage-Calculator#108]
![Fishious Rend V Heliolisk](https://user-images.githubusercontent.com/60319874/73137127-0cbd7f80-4023-11ea-964d-9e569e0298ae.PNG)

Was doing some Calcs, the attached image is exactly how i had the page set up.  The sets for Heliolisk and Dracovish are just the defaults, only change is the sun is activated.  It fails to calculate Fishous rend for whatever reason here.

**Comment by jake-white** [comment]
Dry Skin.

**Comment by schmoounit** [comment]
Omg i never changed the ability. I’m an absolute baffoon. Thank you so much
hahaha
