### ISSUE TITLE
 Can you add a license?

### ISSUE THREAD

**Issue by daynt** [jake-white/VGC-2016-Damage-Calculator#11]
I really like your project. I would like to help you with your project. 
Unfortunately, I have no permission to modify/fork/share your project.
http://choosealicense.com/no-license/

Can you add a license?

**Comment by jake-white** [comment]
Probably won't be adding a license, it's not my place to do so. This was an unofficial fork of Nuggetbridge's calc for VGC 2015 (http://nuggetbridge.com/damagecalc/) (which didn't have a license)

**Comment by Koushien** [comment]
It is your place to do so. The original is MIT'd. https://raw.githubusercontent.com/Zarel/honko-damagecalc/master/LICENSE

**Comment by jake-white** [comment]
Added MIT License.
