### ISSUE TITLE
Modularize damage script

### ISSUE THREAD

**Issue by ajhyndman** [jake-white/VGC-2016-Damage-Calculator#121]
Hi!  This is really just a question for you, @jake-white.

First, thanks for open sourcing your work here!  It's really impressive that you got such a complete and accurate damage calculator out so fast.  

I also work with JavaScript at my day job, and play some Pokemon.  I have some ideas bouncing around in my head for tools that could be neat to build for the myself and the community.  For some of those, it would be really useful to be able to calculate pokemon damage.  I could rewrite or copy-paste a lot of what you've done here, but it seems like we might be duplicating a lot of effort if we both try to stay up to date.

Are you interested in coordinating to make the damage calculation reusable, and then sharing the maintenance effort?

**Comment by ajhyndman** [comment]
In case anyone stumbles on this, it looks like there's a similar effort already underway with the pokemon showdown damage calculator, which I ended up relying on for my project.

https://github.com/smogon/damage-calc

**Comment by scheibo** [comment]
FWIW, @jake-white, if you're at all interested I'd love to help get you guys using the `@smogon/calc` package as well (youve fixed some bugs in your fork that we'd benefit from and vice versa). Overall I think it would be a net win if we could pool our efforts on the mechanics front and differentiate at the UI level instead. Feel free to reach out to me here, on Discord (pre#1111) or via email (pre@smogon.com). Cheers!
