### ISSUE TITLE
Custom sets not working

### ISSUE THREAD

**Issue by archer3cl** [jake-white/VGC-2016-Damage-Calculator#15]
Tried locally, tried on http://jake-white.github.io/VGC-Damage-Calculator/ and they are not working.

Ex:

Porygon2 @ Eviolite  
Ability: Download  
Level: 50  
EVs: 244 HP / 252 SpA / 12 SpD  
Modest Nature  
IVs: 0 Atk  
- Recover  
- Thunderbolt  
- Shadow Ball  
- Ice Beam

**Comment by jake-white** [comment]
Fixed with the trainertower update.
