### ISSUE TITLE
Missing moves

### ISSUE THREAD

**Issue by jake-white** [jake-white/VGC-2016-Damage-Calculator#21]
Razor Leaf/Fly are missing and are now competitively relevant (what a world we live in)

**Comment by Kuriboh3721** [comment]
Beat up is also missing

**Comment by jake-white** [comment]
Razor Leaf/Fly are in the calc now, fixed by 5e8fbf9. Since beat up uses the base stats of up to 6 pokemon to calculate BP + the user's attack vs target defense, it wouldn't really be feasible in a 1v1 calculator.

**Comment by Kuriboh3721** [comment]
Nice!, keep up the good work.
