### ISSUE TITLE
A bug with the ability Fluffy

### ISSUE THREAD

**Issue by JAlexL07** [jake-white/VGC-2016-Damage-Calculator#27]
Some attacks (Liquidation, Lunge, Leech Life) doesn't reduce their damage in half against Fluffy

![fluffy](https://cloud.githubusercontent.com/assets/12719389/26231921/5cedbbc8-3c20-11e7-9cd8-c5c244892786.png)

![nofluffy](https://cloud.githubusercontent.com/assets/12719389/26231922/5cffe82a-3c20-11e7-8557-713c5e8063e2.png)

**Comment by jake-white** [comment]
Yeah contact is messed up for those moves. Fixing for next update.
