### ISSUE TITLE
signature z moves

### ISSUE THREAD

**Issue by cantsay** [jake-white/VGC-2016-Damage-Calculator#28]
if you want to calc a signature Z move you have to manually select that move in the moves dropdown, because clicking Z move on sparkling aria (for example) will turn it into the default 175 bp Hydro Vortex instead of the 195 bp Oceanic Operetta. 

Pokemon Showdown's damage calculator has Z crystals as hold items, and if you have the corresponding Z crystal and click Z move on that attack, it becomes the signature Z move instead of the generic one.

**Comment by jake-white** [comment]
Overall not very user-friendly, I think the current implementation is preferred.
If a lot of people want it this way I could reopen this issue, until then I'll close it.
