### ISSUE TITLE
Wrong damage text?

### ISSUE THREAD

**Issue by ghost** [jake-white/VGC-2016-Damage-Calculator#45]
Was running some calcs for Thunder Tapu Koko and this happened:

**252+ SpA Life Orb Tapu Koko Thunder vs. 220 HP / 92+ SpD Cresselia in Electric Terrain: 109-130 (48.8 - 58.2%) -- 87.5% chance to OHKO**

**252+ SpA Magnet Tapu Koko Thunder vs. 220 HP / 92+ SpD Cresselia in Electric Terrain: 102-121 (45.7 - 54.2%) -- 56.3% chance to OHKO**

This is definitely not a OHKO, so not sure why I'm getting that message. Thunderbolt incorrectly displays as a 2HKO as well:

**252+ SpA Life Orb Tapu Koko Thunderbolt vs. 220 HP / 92+ SpD Cresselia in Electric Terrain: 90-107 (40.3 - 47.9%) -- guaranteed 2HKO**

**Comment by jake-white** [comment]
Sounds like you have the target's HP at less than full my dude

**Comment by ghost** [comment]
I was trying to figure this out for like an hour

this Cresselia is in fact at 50% HP

I am sorry, and also thank you.
