### ISSUE TITLE
Belly Drum support

### ISSUE THREAD

**Issue by baudtack** [jake-white/VGC-2016-Damage-Calculator#50]
Trying to do some calcs on my new team with Belly Drum Azumaril and can't seem to find out how to do that. Is there belly drum support and i'm just to thick to figure it out?

**Comment by Koushien** [comment]
On the normal 1v1 calculator you can set the stages to a stat with the neighboring dropdown (default "--"). Belly Drum sets its user to +6.

**Comment by baudtack** [comment]
AH! Thanks
