### ISSUE TITLE
Various VGC 19 things

### ISSUE THREAD

**Issue by DaWoblefet** [jake-white/VGC-2016-Damage-Calculator#57]
Just keeping these all here because I get random messages telling me to tell you, so here we go:

- Zygarde-Complete and Zygarde-10% don't have correct base HP
- Thousand Arrows and Thousand Waves don't exist
- People want a Geomancy button (probably can replace Kommo-o)

**Comment by DaWoblefet** [comment]
Modifiers to physical Photon Geyser aren't being applied at all; e.g. Choice Band Photon Geyser from Dusk Mane should be dealing increased damage, and burned Dusk Mane should be dealing less damage with Photon Geyser (ofc, Choice Band, burn, etc. do not affect whether or not Photon Geyser is physical/special; it's only the +6 to -6 boosts and the raw stat).

**Comment by jake-white** [comment]
lol turns out that alternate forms don't change the HP stat, for some reason. (I knew I put them in there correctly...) I'll fix that asap and then do the other things when I get a chance

**Comment by jake-white** [comment]
Also, Bulbapedia says "a Flying-type Pokémon not already grounded will receive neutral damage from Thousand Arrows, regardless of its secondary type", do you know if this is true? I assume it is just seems a little strange and pretty relevant.

**Comment by DaWoblefet** [comment]
Yes, it is true (you can see in Mechanics Monday at this timestamp here: https://youtu.be/x4Xgc3JNUz0?t=13m40s). I show that Zapdos and Ledian take neutral damage on the first hit.

**Comment by jake-white** [comment]
Sweet, thanks!
