### ISSUE TITLE
Incorrect calc

### ISSUE THREAD

**Issue by jamesqo** [jake-white/VGC-2016-Damage-Calculator#77]
Repro: For Pokemon 1 choose Tyranitar > Default Set. For Pokemon 2 choose Eternatus > Default Set. Set moves 1 and 2 of Tyranitar to Stone Edge / Earthquake. These are the resulting calcs:

> 252 Atk Tyranitar Stone Edge vs. 0 HP / 0 Def Eternatus: 93-109 (43.2 - 50.6%) -- 46.5% chance to 2HKO after sandstorm damage
> 
> 252 Atk Tyranitar Earthquake vs. 0 HP / 0 Def Eternatus: 92-110 (42.7 - 51.1%) -- 52.3% chance to 2HKO after sandstorm damage

This seems incorrect since Stone Edge has an effective BP 150 (STAB) and Earthquake has an effective BP of 200 (super effective).

**Comment by jake-white** [comment]
Spread moves do 75% damage in doubles.

**Comment by jamesqo** [comment]
Ah, got it.
