### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by michelmau5** [jake-white/VGC-2016-Damage-Calculator#99]
So I came across a wrong calculation result.

252+ SpA Choice Specs Duraludon Thunderbolt vs. 252 HP / 124 SpD Pyukumuku on a critical hit: 174-206 (53.7 - 63.5%) -- guaranteed 2HKO after Leftovers recovery (both lvl 50)

I got 1HKO

This is the smogon calculator which looks right to me:
252+ SpA Choice Specs Duraludon Thunderbolt vs. 252 HP / 124 SpD Pyukumuku on a critical hit: 174-206 (107.4 - 127.1%) -- guaranteed OHKO

![Knipsel](https://user-images.githubusercontent.com/59443177/71670450-25ae7a00-2d70-11ea-9520-46aeea77ea5c.PNG)

**Comment by jake-white** [comment]
You clearly have Dynamax enabled, the actual HP calculation 174-206 are identical.
